config/routes.rb
Rails.application.routes.draw do
  #home
  root to: 'gossips#index'

  #pages menu
  get '/team', to: 'pages#team'
  get '/contact', to: 'pages#contact'

  #gossips
  resources :gossips do
    resources :comments, only: [:create, :edit, :update, :destroy]
    resources :like, only: [:create, :destroy]
  end

  #users
  resources:users, only: [:new, :create, :show]

  #cities
  resources:cities, only: [:show]

  #login/logout
  resources:sessions, only: [:new, :create, :destroy]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
  has_many :users 
  validates :name, presence: true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :gossip
  has_many :likes, as: :content
end

app/models/gossip.rb
class Gossip < ApplicationRecord
  validates :title,
    presence: true,
    length: { minimum: 3, too_short: "%{count} characters is the minimum allowed", maximum: 25, too_long: "%{count} characters is the maximum allowed" }
  validates :content,
    presence: true
  belongs_to :user
  has_many :join_table_tag_gossips
  has_many :tags, through: :join_table_tag_gossips
  has_many :comments
  has_many :users, through: :comments
  has_many :likes, as: :content
end

app/models/join_pm_receiver.rb
class JoinPmReceiver < ApplicationRecord
  belongs_to :private_message
  belongs_to :recipient, class_name: "User"
end

app/models/join_table_tag_gossip.rb
class JoinTableTagGossip < ApplicationRecord
  belongs_to :tag
  belongs_to :gossip
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :content, :polymorphic => true
end

app/models/private_message.rb
class PrivateMessage < ApplicationRecord
  belongs_to :sender, class_name: "User"
  has_many :join_pm_receivers
  has_many :recipients, class_name: "User", through: :join_pm_receivers
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :join_table_tag_gossips
  has_many :gossips, through: :join_table_tag_gossips
end

app/models/user.rb
class User < ApplicationRecord
  belongs_to :city
  validates :email, 
    presence: true,
    uniqueness: true,
    format: { with: /\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/, message: "email adress please" }
  has_secure_password
  validates :password, 
    presence: true, 
    length: { minimum: 6 }
  has_many :comments
  has_many :gossips, through: :comment
  has_many :sent_messages, foreign_key: 'sender_id', class_name: "PrivateMessage"
  has_many :received_messages, foreign_key: 'recipient_id', class_name: "PrivateMessage"
  has_many :likes
end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController
  before_action :authenticate_user

  def show
    @current_city = City.find(params[:id])
  end
end

app/controllers/gossips_controller.rb
class GossipsController < ApplicationController
  before_action :authenticate_user, except: [:index]

  def index
  end

  def show
    @gossip = Gossip.find(params[:id])
    @comment = Comment.new
    @tags = JoinTableTagGossip.all.map{|join| join.gossip_id == @gossip.id ? join.tag.title : nil}.compact
    @likes = @gossip.likes

    @comments = @gossip.comments
  end

  def new
    @gossip = Gossip.new
    @tag = JoinTableTagGossip.new
    @tags = Tag.all
  end

  def create
    @tags = Tag.all
    @gossip = Gossip.new(title: params[:title], content: params[:content], user_id: params[:user])
    if @gossip.save && params[:tag] != ""
      @tag = JoinTableTagGossip.create(tag_id: Tag.find(params[:tag]).id, gossip_id: @gossip.id) 
      render :index
    elsif @gossip.save && params[:tag] == ""
      render :index
    else
      render :new
    end
  end

  def edit
    @tags = Tag.all
    @gossip = Gossip.find(params[:id])
    @current_tags = JoinTableTagGossip.all.map{|join| join.gossip_id == @gossip.id ? join.tag : nil}.compact
  end

  def update
    show
    if @gossip.update(title: params[:title], content: params[:content])
      JoinTableTagGossip.create(tag_id: Tag.find(params[:tag]).id, gossip_id: @gossip.id)  unless params[:tag] == ""
      JoinTableTagGossip.find_by(tag_id: Tag.find(params[:delete_tag]).id, gossip_id: @gossip.id).destroy unless params[:delete_tag] == ""
      show
      render :show
    end
  end

  def destroy
    @gossip = Gossip.find(params[:id])
    if @gossip.destroy
      render :index
    else
      render :show
    end
  end
end

app/controllers/like_controller.rb
class LikeController < ApplicationController
  before_action :authenticate_user

  def create
    @like = Like.new(user_id: current_user.id, content_type: "Gossip", content_id: params[:gossip_id])
    @gossip = Gossip.find(params[:gossip_id])
    @likes = @gossip.likes
    if @likes.map{|like| like.user_id == current_user.id ? like : nil}.compact == []
      @like.save
      redirect_back(fallback_location: root_path)
    else 
      redirect_back(fallback_location: root_path)
    end
  end

  def destroy
    @gossip = Gossip.find(params[:gossip_id])
    @likes = @gossip.likes
    if @likes.map{|like| like.user_id == current_user.id ? like : nil}.compact != []
      @like = Like.find_by(user_id: current_user.id, content_type: "Gossip", content_id: params[:gossip_id]).delete
      redirect_back(fallback_location: root_path)
    else 
      redirect_back(fallback_location: root_path)
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def contact
  end

  def team
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def new
    if current_user
      redirect_to '/'
    end
    @user = User.new
    @age = [7..77]
  end

  def create
    if current_user
      redirect_to '/'
    end
    @city = City.find_by(name: params[:city])

    if @city == nil
      @city = City.create(name: params[:city])
    end

    @user = User.new(
      first_name: params[:first_name], 
      last_name: params[:last_name], 
      description: params[:description],
      email: params[:email],
      password: params[:password], 
      password_confirmation: params[:passwordconfirm],
      age: params[:age],
      city_id: @city.id
    )

    if @user.save
      log_in(@user)
      render 'gossips/index'
    else
      render :new
    end
  end

  def show
    @current_user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/gossips_helper.rb
module GossipsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    User.find_by(id: session[:user_id])
  end

   def log_in(user)
    session[:user_id] = user.id
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/cities/show.html.erb
  <h1><%= @current_city.name %></h1>

<main class="container">
  <h3>Les autres potins de la ville</h3>
  <div class="row row-cols-5 d-flex justify-content-center">
    <% Gossip.all.each do |gossip| %>
      <% if gossip.user.city_id == @current_city.id %>
        <div class="card border-info text-center bg-light my-3 mx-3" style="max-width: 18rem;"> 
          <div class="card-body">
            <h5 class="card-title"><%= gossip.user.first_name %></h5>
            <p class="card-text"><%= gossip.title %></p>
          </div>
          <div class="card-footer">
          <%= gossip.likes.count %>
            <%if current_user %>
              <% if gossip.likes.map{|like| like.user_id == current_user.id ? like : nil}.compact == [] %>
                <%= link_to "", gossip_like_index_path(gossip.id), class:"far fa-heart mx-1 my-1", style:"color:#ff565d;", data:{method:"POST"} %>
              <%else%>
                <%= link_to "", gossip_like_path(gossip.id, current_user.id), class:"fas fa-heart mx-1 my-1", style:"color:#ff565d;", data:{method:"DELETE"} %>
              <%end%>
            <%else%>
              <%= link_to "", gossip_like_index_path(gossip.id), class:"far fa-heart mx-1 my-1", style:"color:#ff565d;", data:{method:"POST"} %>
            <%end%>
            <%= link_to "Voir plus", gossip_path(gossip.id), class:"btn btn-outline-info" %>
            <% if current_user%>
              <% if current_user.id == gossip.user_id%>
                <%= link_to "", user_path(current_user.id), class:"fas fa-star mx-1 my-1", style:"color:#efd807;" %>
              <% end %>
            <% end %>
           </div>
        </div>
      <% end %>
    <% end %>
  </div>
</main>

app/views/gossips/edit.html.erb
<% if @gossip.errors.any? %>
    <% @gossip.errors.full_messages.each do |message| %>
      <p class="alert alert-danger d-flex justify-content-center" role="alert"><%= message %></p>
    <% end %>
<% end %>

<div class="container mt-2 form-group">
 <%= form_tag url_for(action: 'update'), method: "patch" do %>
      <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

      <strong><%= label_tag 'Titre du potin' %></strong>
      <%= text_field_tag 'title', @gossip.title, class:"form-control", required: true %>
      <br /> 

      <strong><%= label_tag 'Contenu du potin' %></strong>
      <%= text_area_tag 'content', @gossip.content, class:"form-control", required: true %>
      <br /> 

      <div class="d-flex justify-content-center"><strong class="mx-2"><%= label_tag 'Tags actuels : ' %></strong>
      <% @current_tags.each do |tag| %>
        <%=tag.title%>
      <% end %></div>

      <strong><%= label_tag 'Ajouter un tag' %></strong>
      <%=select_tag "tag", options_from_collection_for_select(@tags, :id, :title), class:"form-control", include_blank: true%>
      <br /> 

      <strong><%= label_tag 'Supprimer un tag' %></strong>
      <%=select_tag "delete_tag", options_from_collection_for_select(@current_tags, :id, :title), class:"form-control", include_blank: true%>
      <br /> 

      <div class="d-flex justify-content-center"><%= submit_tag "Editer le potin", class:"btn btn-success btn-lg"%></div>

    <% end %>
    <hr>
    <div style="margin-top: 10px;" class="d-flex justify-content-center"><%= link_to "Retour Accueil", root_path, :class => "btn btn-info btn-sm" %></div>
</div>

app/views/gossips/index.html.erb
<% if params[:action] == "create" && params[:commit] == "Créer un potin" %>
  <div class="container alert alert-success d-flex justify-content-center alert-dismissible fade show" role="alert">The super potin was succesfully saved !
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% elsif params[:action] == "create" && params[:commit] == "S'inscrire" %>
  <div class="container alert alert-success d-flex justify-content-center alert-dismissible fade show" role="alert">Un super user was succesfully created !
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% elsif params[:action] == "destroy" %>
  <div class="container alert alert-success d-flex justify-content-center alert-dismissible fade show" role="alert">The shitty potin was motherfucking deleted !
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

<div>
  <%if session[:user_id] != nil%>
    <h1>Bienvenue <%= current_user.first_name %></h1>
  <%else %>
    <%if params[:first_name] == nil%>
      <h1>Bienvenue cher Visiteur</h1>
    <%elsif params[:action] == "create" && params[:commit] == "S'inscrire"%>
      <h1>Bienvenue parmi nous <%= params[:first_name] %></h1>
    <%else %>
      <h1>Bienvenue <%= params[:first_name] %></h1>
  <% end %>
  <% end %>
</div>

<div class="container d-flex justify-content-center" style="margin-bottom: 20px; margin-top: 20px;"><%= link_to "Nouveau potin", new_gossip_path, :class => "btn btn-info" %></div>

<main class="container">
  <h3>Voici la liste des potins les plus croustillants du web :</h3>
  <p>Cliquez sur le potin de votre choix pour en savoir plus ;)</p>
  <div class="row row-cols-5 d-flex justify-content-center">
    <% Gossip.all.sort.each do |gossip| %>
      <div class="card border-info text-center bg-light my-3 mx-3" style="max-width: 18rem;"> 
        <div class="card-body">
          <h5 class="card-title"><%= gossip.user.first_name %></h5>
          <p class="card-text"><%= gossip.title %></p>
        </div>
        <div class="card-footer">
          <%= gossip.likes.count %>
            <%if current_user %>
              <% if gossip.likes.map{|like| like.user_id == current_user.id ? like : nil}.compact == [] %>
                <%= link_to "", gossip_like_index_path(gossip.id), class:"far fa-heart mx-1 my-1", style:"color:#ff565d;", data:{method:"POST"} %>
              <%else%>
                <%= link_to "", gossip_like_path(gossip.id, current_user.id), class:"fas fa-heart mx-1 my-1", style:"color:#ff565d;", data:{method:"DELETE"} %>
              <%end%>
            <%else%>
              <%= link_to "", gossip_like_index_path(gossip.id), class:"far fa-heart mx-1 my-1", style:"color:#ff565d;", data:{method:"POST"} %>
            <%end%>
          <%= link_to "Voir plus", gossip_path(gossip.id), class:"btn btn-outline-info mx-1 my-1" %>
          <% if current_user%>
            <% if current_user.id == gossip.user_id%>
              <%= link_to "", user_path(current_user.id), class:"fas fa-star mx-1 my-1", style:"color:#efd807;" %>
            <% end %>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>
</main>

app/views/gossips/new.html.erb
<% if @gossip.errors.any? %>
    <% @gossip.errors.full_messages.each do |message| %>
      <div class="container alert alert-danger d-flex justify-content-center alert-dismissible fade show" role="alert"><%= message %>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
    <% end %>
<% end %>

<div class="container mt-5 form-group">
 <%= form_tag url_for(action: 'create'), method: "post" do %>
      <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

      <strong><%= label_tag 'Titre du potin' %></strong>
      <%= text_field_tag 'title', @gossip.title, class:"form-control" %>
      <br /> 

      <strong><%= label_tag 'Contenu du potin' %></strong>
      <%= text_area_tag 'content', @gossip.content, class:"form-control" %>
      <br /> 

      <strong><%= label_tag 'Ajouter un tag' %></strong>
      <%=select_tag "tag", options_from_collection_for_select(@tags, :id, :title), class:"form-control", include_blank: true%>
      <br /> 

     <input type="hidden" name="user" value=<%= current_user.id %>>

      <div class="d-flex justify-content-center"><%= submit_tag "Créer un potin", class:"btn btn-success btn-lg"%></div>

    <% end %>
        <hr>
    <div style="margin-top: 10px;" class="d-flex justify-content-center"><%= link_to "Retour Accueil", root_path, :class => "btn btn-info btn-sm" %></div>
</div>

app/views/gossips/show.html.erb
<% if params[:action] == "update" %>
  <div class="container alert alert-success d-flex justify-content-center alert-dismissible fade show" role="alert">The super potin was succesfully edited !
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

<h1 class="d-flex flex-row justify-content-center my-5">Vous êtes sur le potin de <%= @gossip.user.first_name %> <%= @gossip.user.last_name %></h1>


<main class="container">
<div style="margin-bottom: 20px;" class="d-flex flex-row justify-content-between">
  <div>
    <% if current_user.id == @gossip.user_id%>
      <%= link_to "Editer", edit_gossip_path(@gossip.id), class:"btn btn-outline-success mx-1 my-1" %>
      <%= link_to "Supprimer", gossip_path(@gossip.id), class:"btn btn-outline-danger mx-1 my-1", data:{confirm:"Etes vous sûr de vouloir supprimer ce potin ?", method:"DELETE"} %>
    <% end %>
    <%= link_to "Retour Accueil", root_path, :class => "btn btn-info" %>
  </div>
  <div class="d-flex flex-row justify-content-center">
    <h3 class="mx-2"><%= @likes.count %></h3> 
    <% if @likes.map{|like| like.user_id == current_user.id ? like : nil}.compact == [] %>
      <%= link_to "", gossip_like_index_path(@gossip.id), class:"far fa-heart fa-2x mx-1 my-1", style:"color:#ff565d;", data:{method:"POST"} %>
    <%else%>
      <%= link_to "", gossip_like_path(@gossip.id, current_user.id), class:"fas fa-heart fa-2x mx-1 my-1", style:"color:#ff565d;", data:{method:"DELETE"} %>
    <%end%>
  </div>
</div>
<div class="card">
  <div class="card-header">
    <%= @gossip.title %>
  </div>
  <div class="card-body">
    <blockquote class="blockquote mb-0">
      <p><%= @gossip.content %></p>
      <footer class="blockquote-footer"><%= link_to "#{@gossip.user.first_name} #{@gossip.user.last_name}", user_path(@gossip.user.id) %> à <%= link_to "#{@gossip.user.city.name}", city_path(@gossip.user.city.id) %></footer>
    </blockquote>
  </div>
</div>

<hr>
<div class="d-flex flex-row justify-content-center align-items-center">
  <div>
    <% @tags.each do |tag| %>
      <%=tag%>
    <% end %>
  </div>
</div>

<hr>

<h2>Commentaires</h2>

<div>
  <%= render 'comments/index'%>
  <%= render 'comments/new'%>
</div>
</main>
<hr>

app/views/users/new.html.erb
<% if @user.errors.any? %>
    <% @user.errors.full_messages.each do |message| %>
      <div class="container alert alert-danger d-flex justify-content-center alert-dismissible fade show" role="alert"><%= message %>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
    <% end %>
<% end %>

<div class="container mt-5 form-group">
 <%= form_tag url_for(action: 'create'), method: "post" do %>
      <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

      <strong><%= label_tag 'Prénom' %></strong>
      <%= text_field_tag 'first_name', @user.first_name, class:"form-control", required: true %>
      <br /> 

      <strong><%= label_tag 'Nom' %></strong>
      <%= text_field_tag 'last_name', @user.last_name, class:"form-control", required: true %>
      <br /> 

      <strong><%= label_tag 'Description' %></strong>
      <%= text_area_tag 'description', @user.description, class:"form-control", required: true %>
      <br /> 

      <strong><%= label_tag 'e-mail' %></strong>
      <%= text_field_tag 'email', @user.email, class:"form-control", required: true %>
      <br /> 

      <strong><%= label_tag 'Mot de passe' %></strong>
      <%= text_field_tag 'password', @user.password, class:"form-control", type:"password", required: true %>
      <br /> 

      <strong><%= label_tag 'Confirmation du mot de passe' %></strong>
      <%= text_field_tag 'passwordconfirm', @user.password_confirmation, class:"form-control", type:"password", required: true %>
      <br /> 

      <strong><%= label_tag 'Age' %>
      <%= text_field_tag 'age', @user.age, class:"form-control", required: true %></strong>
      <br /> 

      <strong><%= label_tag 'City' %>
      <%= text_field_tag 'city', @user.city, class:"form-control", required: true %></strong>
      <br /> 

      <div class="d-flex justify-content-center"><%= submit_tag "S'inscrire", class:"btn btn-success btn-lg"%></strong></div>

    <% end %>
</div>

app/views/users/show.html.erb
  <h1>Profil de <%= @current_user.first_name %> <%= @current_user.last_name %></h1>

<main class="container">
<div class="card" >
  <ul class="list-group list-group-flush">
    <li class="list-group-item">Description : <%= @current_user.description %></li>
    <li class="list-group-item">Email : <%= @current_user.email %></li>
    <li class="list-group-item">Age : <%= @current_user.age %></li>
    <li class="list-group-item">Ville : <%= link_to "#{@current_user.city.name}", city_path(@current_user.city.id) %></li>
  </ul>
</div>

  <h3>Les autres potins de l'auteur</h3>
  <div class="row row-cols-5 d-flex justify-content-center">
    <% Gossip.all.each do |gossip| %>
      <% if gossip.user_id == @current_user.id %>
        <div class="card border-info text-center bg-light my-3 mx-3" style="max-width: 18rem;"> 
          <div class="card-body">
            <h5 class="card-title"><%= gossip.user.first_name %></h5>
            <p class="card-text"><%= gossip.title %></p>
          </div>
          <div class="card-footer">
          <%= gossip.likes.count %>
            <%if current_user %>
              <% if gossip.likes.map{|like| like.user_id == current_user.id ? like : nil}.compact == [] %>
                <%= link_to "", gossip_like_index_path(gossip.id), class:"far fa-heart mx-1 my-1", style:"color:#ff565d;", data:{method:"POST"} %>
              <%else%>
                <%= link_to "", gossip_like_path(gossip.id, current_user.id), class:"fas fa-heart mx-1 my-1", style:"color:#ff565d;", data:{method:"DELETE"} %>
              <%end%>
            <%else%>
              <%= link_to "", gossip_like_index_path(gossip.id), class:"far fa-heart mx-1 my-1", style:"color:#ff565d;", data:{method:"POST"} %>
            <%end%>
            <%= link_to "Voir plus", gossip_path(gossip.id), class:"btn btn-outline-info" %>
            <% if current_user%>
              <% if current_user.id == gossip.user_id%>
                <%= link_to "", user_path(current_user.id), class:"fas fa-star mx-1 my-1", style:"color:#efd807;" %>
              <% end %>
            <% end %>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
</main>