config/routes.rb
Rails.application.routes.draw do
  #home
  root to: 'gossips#index'

  #pages menu
  get '/team', to: 'pages#team'
  get '/contact', to: 'pages#contact'

  #gossips
  resources :gossips do
    resources :comments, only: [:create, :edit, :update, :destroy]
    resources :like, only: [:create, :destroy]
  end

  #users
  resources:users, only: [:new, :create, :show]

  #cities
  resources:cities, only: [:show]

  #login/logout
  resources:sessions, only: [:new, :create, :destroy]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
  has_many :users 
  validates :name, presence: true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :gossip
  has_many :likes, as: :content
end

app/models/gossip.rb
class Gossip < ApplicationRecord
  validates :title,
    presence: true,
    length: { minimum: 3, too_short: "%{count} characters is the minimum allowed", maximum: 25, too_long: "%{count} characters is the maximum allowed" }
  validates :content,
    presence: true
  belongs_to :user
  has_many :join_table_tag_gossips
  has_many :tags, through: :join_table_tag_gossips
  has_many :comments
  has_many :users, through: :comments
  has_many :likes, as: :content
end

app/models/join_pm_receiver.rb
class JoinPmReceiver < ApplicationRecord
  belongs_to :private_message
  belongs_to :recipient, class_name: "User"
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :content, :polymorphic => true
end

app/models/private_message.rb
class PrivateMessage < ApplicationRecord
  belongs_to :sender, class_name: "User"
  has_many :join_pm_receivers
  has_many :recipients, class_name: "User", through: :join_pm_receivers
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :join_table_tag_gossips
  has_many :gossips, through: :join_table_tag_gossips
end

app/models/user.rb
class User < ApplicationRecord
  belongs_to :city
  validates :email, 
    presence: true,
    uniqueness: true,
    format: { with: /\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/, message: "email adress please" }
  has_secure_password
  validates :password, 
    presence: true, 
    length: { minimum: 6 }
  has_many :comments
  has_many :gossips, through: :comment
  has_many :sent_messages, foreign_key: 'sender_id', class_name: "PrivateMessage"
  has_many :received_messages, foreign_key: 'recipient_id', class_name: "PrivateMessage"
  has_many :likes
end

app/controllers/like_controller.rb
class LikeController < ApplicationController
  before_action :authenticate_user

  def create
    @like = Like.new(user_id: current_user.id, content_type: "Gossip", content_id: params[:gossip_id])
    @gossip = Gossip.find(params[:gossip_id])
    @likes = @gossip.likes
    if @likes.map{|like| like.user_id == current_user.id ? like : nil}.compact == []
      @like.save
      redirect_back(fallback_location: root_path)
    else 
      redirect_back(fallback_location: root_path)
    end
  end

  def destroy
    @gossip = Gossip.find(params[:gossip_id])
    @likes = @gossip.likes
    if @likes.map{|like| like.user_id == current_user.id ? like : nil}.compact != []
      @like = Like.find_by(user_id: current_user.id, content_type: "Gossip", content_id: params[:gossip_id]).delete
      redirect_back(fallback_location: root_path)
    else 
      redirect_back(fallback_location: root_path)
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def contact
  end

  def team
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def new
    if current_user
      redirect_to '/'
    end
    @user = User.new
    @age = [7..77]
  end

  def create
    if current_user
      redirect_to '/'
    end
    @city = City.find_by(name: params[:city])

    if @city == nil
      @city = City.create(name: params[:city])
    end

    @user = User.new(
      first_name: params[:first_name], 
      last_name: params[:last_name], 
      description: params[:description],
      email: params[:email],
      password: params[:password], 
      password_confirmation: params[:passwordconfirm],
      age: params[:age],
      city_id: @city.id
    )

    if @user.save
      log_in(@user)
      render 'gossips/index'
    else
      render :new
    end
  end

  def show
    @current_user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/gossips_helper.rb
module GossipsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    User.find_by(id: session[:user_id])
  end

   def log_in(user)
    session[:user_id] = user.id
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>The Gossip Project</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://kit.fontawesome.com/f56b9447bd.js" crossorigin="anonymous"></script>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
  </head>

  <body>
  <nav class="navbar navbar-expand-sm bg-dark navbar-dark">
      <%= link_to "The Gossip Project", root_path, :class => "navbar-brand" %>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse d-flex justify-content-between" id="collapsibleNavbar">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item <%= 'active' if current_page?(root_path) %>">
            <%= link_to "Accueil", root_path, :class => "nav-link" %>
          </li>
          <li class="nav-item <%= 'active' if current_page?(team_path) %>">
            <%= link_to "Team", team_path, :class => "nav-link" %>
          </li>
          <li class="nav-item <%= 'active' if current_page?(contact_path) %>">
            <%= link_to "Contact", contact_path, :class => "nav-link" %>
          </li>
        </ul>
        <ul class="navbar-nav">
          <% if session[:user_id] == nil%>
            <li class="btn-group">
              <button type="button" class="btn btn-secondary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                S'inscrire / Se connecter
              </button>
              <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                <%= link_to "Inscription", new_user_path, :class => "dropdown-item" %>
                <div class="dropdown-divider"></div>
                <%= link_to "Connection", new_session_path, :class => "dropdown-item" %>
              </div>
            </li>
          <% else %>
            <li class="nav-item dropdown">
              <button type="button" class="btn btn-secondary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <%= current_user.first_name + " " + current_user.last_name %>
              </button>
              <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                <%= link_to "Voir profil", user_path(current_user.id), class: "dropdown-item" %>
                <!--<%= link_to "Parametres", user_path(current_user.id), class: "dropdown-item" %>-->
                <div class="dropdown-divider"></div>
                <%= link_to "Se déconnecter", session_path(session.id), class:"dropdown-item", method: :delete %>
              </div>
            </li>
          <% end %>
        </ul>
      </div>
    </nav>
    <header class="container mb-2">
      <%= link_to root_path do %>
        <%= image_tag "/images/banner.png" %>
      <% end %>
    </header>

    <%= yield %>

    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>

  </body>
</html>

app/views/pages/contact.html.erb
  <h1>
    Contact
  </h1>

<main class="container">
  <h2>Vous pouvez nous contacter sur Slack ! On vous répondra avec plaisir =) </h2>

</main>

app/views/pages/team.html.erb
<main class="container my-5" style="margin-top : 20px;">
  <div class="card-deck">
    <div class="card text-center bg-light my-3 mx-3" style="border:none; text-align:right;">
      <img id="bibi" class="card-img-top rounded-circle" src="/images/profil.jpeg" alt="Card image cap">
      <div class="card-body">
        <h5 class="card-title">Luca Montaigut</h5>
        <p class="card-text">Developpeur débutant chez THP</p>
      </div>
    </div>

    <div class="card text-center bg-light my-3 mx-3" style="border:none;">
      <img id="alfred" class="card-img-top rounded-circle" src="/images/baptiste.jpg" alt="Card image cap">
      <div class="card-body">
        <h5 class="card-title">Baptiste</h5>
        <p class="card-text">Developpeur débutant chez THP</p>
      </div>
    </div>

    <div class="card text-center bg-light my-3 mx-3" style="border:none;">
      <img id="alfred" class="card-img-top rounded-circle" src="/images/xuan.jpg" alt="Card image cap">
      <div class="card-body">
        <h5 class="card-title">Xuan</h5>
        <p class="card-text">Developpeuse débutante chez THP</p>
      </div>
    </div>


    <div class="card text-center bg-light my-3 mx-3" style="border:none;">
      <img id="alfred" class="card-img-top rounded-circle" src="/images/marius.jpg" alt="Card image cap">
      <div class="card-body">
        <h5 class="card-title">Marius</h5>
        <p class="card-text">Developpeur débutant chez THP</p>
      </div>
    </div>


  </div>

  <div class="card text-center bg-light my-3 mx-3" style="border:none;">
    <img id="alfred" class="card-img-top rounded-circle" src="/images/alfred.jpg" alt="Card image cap">
    <div class="card-body">
      <h5 class="card-title">Alfred</h5>
      <p class="card-text">Qui nous supporte au quotidien</p>
    </div>
  </div>
</main>
<footer id="lazyrabbit">
  <div>
    <p>  (\(\</p>
    <p>  ( -.-)</p>
    <p>  o_(")(")</p>
  </div>  
</footer>